export const breads = [
  {
    id: 1,
    name: "네모바게트",
    type: "breads",
    src: "Bread1.png",
    hashtags: ["바게트", "바게뜨?", "가로로 긴 바게뜨"],
    like: false,
  },
  {
    id: 2,
    name: "바게트",
    type: "breads",
    src: "Bread2.png",
    hashtags: ["마싯는", "바게뜨?", "생크림이랑", "같이 먹으면", "맛있겠다"],
    like: false,
  },
  {
    id: 3,
    name: "초코 생크림 케이크",
    type: "cakes",
    src: "Bread3.png",
    hashtags: ["장난감?", "한입만", "우유랑", "커피랑"],
    like: false,
  },
  {
    id: 4,
    name: "레드벨벳 케이크",
    type: "cakes",
    src: "Bread4.png",
    hashtags: ["해시", "태그", "입니다", "너무 많다"],
    like: false,
  },
  {
    id: 5,
    name: "레드벨벳 쿠키",
    type: "cookies",
    src: "Bread5.png",
    hashtags: ["해시", "태그", "입니다", "너무 많다"],
    like: false,
  },
  {
    id: 6,
    name: "초코칩 쿠키",
    type: "cookies",
    src: "Bread6.png",
    hashtags: ["해시", "태그", "입니다", "너무 많다"],
    like: false,
  },
  {
    id: 7,
    name: "바게트 (묶음)",
    type: "breads",
    src: "Bread7.png",
    hashtags: ["해시", "태그", "입니다", "너무 많다"],
    like: false,
  },
  {
    id: 8,
    name: "딸기케이크",
    type: "cakes",
    src: "Bread8.png",
    hashtags: ["해시", "태그", "입니다", "너무 많다"],
    like: false,
  },
  {
    id: 9,
    name: "로투스 치즈케이크",
    type: "cake",
    src: "Bread9.png",
    hashtags: ["해시", "태그", "입니다", "너무 많다"],
  },
  {
    id: 10,
    name: "베리 치즈케이크",
    type: "cakes",
    src: "Bread10.png",
    hashtags: ["해시", "태그", "입니다", "너무 많다"],
    like: false,
  },
  {
    id: 11,
    name: "식빵",
    type: "breads",
    src: "Bread11.png",
    hashtags: ["해시", "태그", "입니다", "너무 많다"],
    like: false,
  },
];
